export {
    AddIcon,
    AltArrowDownIcon,
    AltArrowLeftIcon,
    AltArrowRightIcon,
    AltArrowUpIcon,
    ArrowDownIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    BoxIcon,
    Buildings2Icon,
    Buildings3Icon,
    BuildingsIcon,
    BusIcon,
    CalendarAddIcon,
    CalendarDateIcon,
    CalendarIcon,
    CalendarMarkIcon,
    CameraIcon,
    ChartIcon,
    ChatRoundDotsIcon,
    ChatRoundIcon,
    ChatRoundUnreadIcon,
    ChatSquareArrowIcon,
    ChatSquareIcon,
    CheckCircleIcon,
    CheckReadIcon,
    ChecklistIcon,
    ClipboardCheckIcon,
    ClipboardListIcon,
    ClockCircleIcon,
    CloseCircleIcon,
    CloseIcon,
    CloudUploadIcon,
    CodeScanIcon,
    CopyIcon,
    DangerCircleIcon,
    DangerTriangleIcon,
    DatabaseIcon,
    DisketteIcon,
    DislikeIcon,
    DocumentTextIcon,
    DownloadIcon,
    EyeClosedIcon,
    EyeIcon,
    FeedIcon,
    FileIcon,
    FilterIcon,
    FlameIcon,
    ForbiddenIcon,
    GalleryIcon,
    GraphUpIcon,
    HamburgerMenuIcon,
    HandHeartIcon,
    HandShakeIcon,
    HeartIcon,
    HeartPulseIcon,
    HistoryIcon,
    HouseIcon,
    InboxIcon,
    InfoCircleIcon,
    KeyIcon,
    LampIcon,
    LeafIcon,
    LetterIcon,
    LibraryIcon,
    LikeIcon,
    LinkIcon,
    ListIcon,
    LockKeyholeIcon,
    LogoutIcon,
    MagnifierIcon,
    MagnifierZoomInIcon,
    MagnifierZoomOutIcon,
    MapIcon,
    MapPointIcon,
    MaximizeIcon,
    MedalRibbonIcon,
    MenuDotsCircleIcon,
    MenuDotsIcon,
    MinimizeIcon,
    MinusIcon,
    MonitorIcon,
    MoonIcon,
    PaletteIcon,
    PaperclipIcon,
    PauseIcon,
    Pen2Icon,
    PenIcon,
    PhoneIcon,
    PieChartIcon,
    PlayIcon,
    PlugCircleIcon,
    PowerIcon,
    PresentationGraphIcon,
    PrinterIcon,
    PulseIcon,
    QuestionCircleIcon,
    QuestionMarkIcon,
    RadarIcon,
    RecordIcon,
    RefreshCircleIcon,
    RefreshIcon,
    ReorderIcon,
    RestartIcon,
    SendSquareIcon,
    ServerIcon,
    SettingsIcon,
    ShieldCheckIcon,
    ShieldCrossIcon,
    ShieldIcon,
    ShieldUserIcon,
    ShieldWarningIcon,
    SortVerticalIcon,
    SquareAcademicCapIcon,
    SquareArrowRightUpIcon,
    SsdRoundIcon,
    StarIcon,
    StructureIcon,
    SuitcaseIcon,
    SunIcon,
    TagHorizontalIcon,
    TagIcon,
    ThreeSquaresIcon,
    ToolboxIcon,
    TransferHorizontalIcon,
    UnlinkIcon,
    UnreadIcon,
    UserCheckRoundedIcon,
    UserCircleIcon,
    UserRoundedIcon,
    UsersGroupRoundedIcon,
    VerifiedCheckIcon,
    WidgetIcon,
} from '@solar-icons/react/outline';

export {
    HeartIcon as HeartBoldIcon,
    StarIcon as StarBoldIcon,
    PlayIcon as PlayBoldIcon,
} from '@solar-icons/react/bold';

export {
    AltArrowDownIcon as ChevronDownIcon,
    AltArrowLeftIcon as ChevronLeftIcon,
    AltArrowRightIcon as ChevronRightIcon,
    AltArrowUpIcon as ChevronUpIcon,
    CheckCircleIcon as CheckIcon,
    MenuDotsIcon as MoreHorizontalIcon,
} from '@solar-icons/react/outline';

// Ícone único de exclusão em todo o sistema (`trash-bin-2-outline`). Os
// consumidores usam o nome TrashBinTrashIcon; trocar o ícone é mudar só aqui.
export { TrashBin2Icon as TrashBinTrashIcon } from '@solar-icons/react/outline';
